[model]
training = true
[model.config]
matrixshape = [224, 224]
batchsize = 64
input_channels = 3
hidden = 80
kernel_size = 4
maxpool = 3
num_layers = 8
num_classes = 5


[types]
training = "bool"
config = "dict"
