[model]
training = false
num_classes = 10
units1 = 128
units2 = 128
units3 = 128
units4 = 128

[types]
training = "bool"
num_classes = "int"
units1 = "int"
units2 = "int"
units3 = "int"
units4 = "int"
